{{- range $npName, $npData:= .Values.nodePools }}
---
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  {{- with $npData.additionalAnnotations }}
  annotations:
    {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
  {{- with $npData.additionalLabels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ $npName }}
spec:
  template:
    {{- with $npData.template.metadata }}
    metadata:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with $npData.template.spec }}
    spec:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  {{- with $npData.disruption }}
  disruption:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $npData.limits }}
  limits:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $npData.weight }}
  weight: {{ . }}
  {{- end }}
{{- end }}