{{- range $nodepoolName, $nodepoolData:= .Values.nodePools }}
---
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: {{ $nodepoolName | trunc 63 | trimSuffix "-" }}
  annotations:
    helm.sh/hook-weight: "10"
  {{- with $nodepoolData.additionalAnnotations }}
    {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
  labels:
    {{- include "karpenter-nodes.labels" (dict "context" $ "component" "nodepool" "name" ($nodepoolName | trunc 63 | trimSuffix "-")) | nindent 4 }}
  {{- with $nodepoolData.additionalLabels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  template:
    {{- with $nodepoolData.template.metadata }}
    metadata:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with $nodepoolData.template.spec }}
    spec:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  {{- with $nodepoolData.disruption }}
  disruption:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $nodepoolData.limits }}
  limits:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $nodepoolData.weight }}
  weight: {{ . }}
  {{- end }}
{{- end }}